# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 897353e70f70d039e16c90c1ebf186e7e75c6a849c7c3b9edc918cdb87c5d94489f0d7bea172d0f925e6785a266d4b48777568f3f39e2ed071e501083179526a

test:
  secret_key_base: 6585cbf4704f8613bcaf19599d2eb76d97c67f042a3a712fd93e8f788fa1326d088d7c8004db937a37712100e094f4620035ed4cc90254f52212e03d2dfca3f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
